class AttributeAdmin:
    URL_ADMIN = 'admin'

    LOGIN_FORM = '.panel-default'
    USERNAME = '#input-username'
    PASSWORD = '#input-password'
    LOGIN = '.btn-primary'
    FORGOTTEN_PASSWORD = 'Forgotten Password'

    MENU_CATALOG = '[href="#collapse1"]'
    CATALOG = '#collapse1'
    PRODUCTS = CATALOG + ' > li:nth-child(2) > a'

    ADD_PRODUCT = '[data-original-title="Add New"]'
    TAB_GENERAL = '[href="#tab-general"]'
    TAB_DATA = '[href="#tab-data"]'
    TAB_SPECIAL = '[href="#tab-special"]'
    PRODUCT_NAME = '#input-name1'
    META_TAG_TITLE = '#input-meta-title1'
    MODEL = '#input-model'
    PRICE_TAB_DATA = '#input-price'
    PRICE_TAB_SECTION = '#special-row0 > td:nth-child(3) > input'
    QUANTITY = '#input-quantity'
    STATUS = '#input-status'
    SORT = '#input-sort-order'
    BUTTON_SAVE = '[data-original-title="Save"]'
    BUTTON_DELETE = '[data-original-title="Delete"]'
    BUTTON_EDIT = '[data-original-title="Edit"]'
    BUTTON_COPY = '[data-original-title="Copy"]'

    COUNT_PAGES = '.col-sm-6.text-right'
    COUNT_PRODUCTS = 'tbody tr'
    TABLE_PROD_NAME = '.text-left'
    TAMLE_PROD_PRICE = '.text-right'
    PRICE_BEFORE = '[style="text-decoration: line-through;"]'
    PRICE_AFTER = '.text-danger'
    ELEMENT_PAGINATION = '.pagination'
    NEXT_PAGE = 'li:nth-child(3) > a'
    PAGE_PRODUCTS = '#content > div.container-fluid > div > div.col-md-9.col-md-pull-3.col-sm-12 > div > div.panel-body > div > div.col-sm-6.text-left > ul > li:nth-child(3) > a'
    ALERT_WARNING = '.alert-danger.alert-dismissible'
    TEXT_WARNING_ALERT = 'Warning: Please check the form carefully for errors!'
    DANGER_TEXT = '.text-danger'
    CHECKBOX_PROD = '[type="checkbox"]'
    ALERT_SUCCESS = '.alert-success'
